### ISSUE TITLE
Home screen not looking good into smaller devices

### ISSUE THREAD

**Issue by giovaninppc** [giovaninppc/AccessibilityHandbook#6]
We need to change how the home is built so it adjusts correctly into any size of device.
We may also make some improvements into the iPad version - which works, but it's not THAT great.

<img width="506" alt="Screen Shot 2022-09-23 at 11 31 49" src="https://user-images.githubusercontent.com/12978176/191984746-3de46aba-d884-45f3-8146-070c80628b6f.png">

**Comment by misteu** [comment]
Hi there,
I'd like to have a look into this during hacktoberfest. :)
Can you assign it to me and add `hacktoberfest` to your repo's topic?

**Comment by misteu** [comment]
Hey,
sorry for my late reply, was on vacation. I think I found a quick fix, will prepare a PR now.
